markdown: kramdown
baseurl: /jkw-blog
exclude: [README.md, Gemfile, Gemfile.lock]
parmalink: pretty
timezone: Asia/Seoul
keep_files: [assets, files]
excerpt_separator: <!--more-->

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

asset_url: /assets

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      permalink: /:year/:month/:day/:title/
  -
    scope:
      path: ""
      type: tags
    values:
      layout: tag
