markdown: kramdown
baseurl: /jkw-blog
url: jeongkiwoon.github.io/jkw-blog
exclude: [README.md, Gemfile, Gemfile.lock]
parmalink: pretty
timezone: Asia/Seoul
keep_files: [assets, files]
excerpt_separator: <!--more-->
title: 'Kiwoon Jeong'
author: 'Kiwoon Jeong'
description: '정기운의 블로그입니다.'


krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 6
paginate_path: '/page/:num/'

asset_url: /assets

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      permalink: /:year/:month/:day/:title/
      author: 'Kiwoon Jeong'
  -
    scope:
      path: ""
      type: tags
    values:
      layout: tag
